name: Homelab Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, homelab]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verificar Docker
        run: docker --version

      - name: Pull imagenes
        run: docker compose -f /root/monitoring/docker-compose.yml pull

      - name: Desplegar stack
        run: |
          docker compose -f /root/monitoring/docker-compose.yml up -d --remove-orphans \
            prometheus \
            grafana \
            blackbox-exporter \
            pihole-exporter \
            homepage \
            node-exporter

      - name: Contenedores activos
        run: docker ps
